CREATE SEQUENCE PWS_SEQUENCE START WITH 100;

CREATE TABLE PLAYER(
    TAG VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    ROLE VARCHAR(255)
);
ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_PK_CONSTRAINT PRIMARY KEY(TAG);

CREATE TABLE PLAYER_WEEKLY_STATS(
    ID BIGINT DEFAULT NEXTVAL('PWS_SEQUENCE') NOT NULL,
    WEEK SMALLINT NOT NULL,
    CARD_DONATION SMALLINT,
    CHEST_CONTRIBUTION SMALLINT,
    AVG_CARD_DONATION REAL DEFAULT 0,
	AVG_CHEST_CONTRIBUTION REAL DEFAULT 0,
    PLAYERFK VARCHAR(255)
);

ALTER TABLE PLAYER_WEEKLY_STATS ADD CONSTRAINT PWS_UNIQUE_1 UNIQUE(PLAYERFK, WEEK);
ALTER TABLE PLAYER_WEEKLY_STATS ADD CONSTRAINT PWS_PLAYER_FK FOREIGN KEY(PLAYERFK) REFERENCES PLAYER(TAG);
ALTER TABLE PLAYER_WEEKLY_STATS ADD CONSTRAINT PWS_PK PRIMARY KEY(ID);
CREATE INDEX PWS_WEEK_INDEX ON PLAYER_WEEKLY_STATS (week);


CREATE TABLE JOB_EXECUTION(
    JOB_ID VARCHAR(100) NOT NULL,
    LATEST_EXECUTION TIMESTAMP NOT NULL
);

ALTER TABLE JOB_EXECUTION ADD CONSTRAINT JOB_EXECUTION_PK_CONSTRAINT PRIMARY KEY(JOB_ID);



