CREATE TABLE CLAN_WEEKLY_STATS(
    WEEK SMALLINT NOT NULL,
    CLAN_CHEST_SCORE REAL,
    CROWN_SCORE REAL,
    PLAYER_DEVIATION_SCORE REAL
);
ALTER TABLE CLAN_WEEKLY_STATS ADD CONSTRAINT CLAN_WEEKLY_STATS_PK PRIMARY KEY(WEEK);

