
CREATE TABLE WEEKLY_JOB(
    LATEST_WEEK SMALLINT NOT NULL
);
ALTER TABLE WEEKLY_JOB ADD CONSTRAINT LATEST_WEEK_CONSTRAINT PRIMARY KEY(LATEST_WEEK);


INSERT INTO PUBLIC.WEEKLY_JOB(LATEST_WEEK) VALUES (35), (36);


