ALTER TABLE PLAYER_WEEKLY_STATS ADD COLUMN CARDS_RECEIVED SMALLINT;
ALTER TABLE PLAYER_WEEKLY_STATS ADD COLUMN TOTAL_CARDS_RECEIVED SMALLINT;
ALTER TABLE PLAYER_WEEKLY_STATS ADD COLUMN TOTAL_CARD_DONATIONS SMALLINT;

