ALTER TABLE PLAYER_WEEKLY_STATS ADD AVG_CARD_DONATION REAL DEFAULT 0;
ALTER TABLE PLAYER_WEEKLY_STATS ADD AVG_CHEST_CONTRIBUTION REAL DEFAULT 0;

ALTER TABLE PLAYER DROP COLUMN AVG_CARD_DONATION;
ALTER TABLE PLAYER DROP COLUMN AVG_CHEST_CONTRIBUTION;