CREATE TABLE PLAYER_AGGREGATION_WAR_STATS (
    ID BIGINT NOT NULL,
    DATE TIMESTAMP NOT NULL,
    LEAGUE_SPAN INTEGER NOT NULL,
    PLAYER_TAG VARCHAR(255) NOT NULL,
    AVG_CARDS REAL,
    AVG_WINS REAL,
    GAMES_GRANTED INTEGER,
    GAMES_NOT_PLAYED INTEGER,
    GAMES_WON INTEGER,
    SCORE INTEGER,
    TOTAL_CARDS INTEGER,
    WARS_ELIGIBLE_FOR_PARTICIPATION INTEGER,
    WARS_PARTICIPATED INTEGER,
    primary key (ID)
);

ALTER TABLE PLAYER_AGGREGATION_WAR_STATS ADD CONSTRAINT PLAYER_AGGR_WAR_STAT_FK_PLAYER FOREIGN KEY(PLAYER_TAG) REFERENCES PLAYER(TAG);
ALTER TABLE PLAYER_AGGREGATION_WAR_STATS ADD CONSTRAINT PLAYER_AGGR_WAR_STAT_BUSSINESS_KEY UNIQUE (date, league_span, player_tag);
CREATE INDEX PLAYER_AGGREGATION_WAR_STATS_INDEX ON PLAYER_AGGREGATION_WAR_STATS (date, league_span, player_tag);










