CREATE TABLE PLAYER_AGGREGATION_WAR_STATS (
    DATE TIMESTAMP NOT NULL,
    LEAGUE_SPAN INTEGER NOT NULL,
    PLAYER_TAG VARCHAR(255) NOT NULL,
    AVG_CARDS DOUBLE,
    AVG_WINS DOUBLE,
    GAMES_GRANTED INTEGER,
    GAMES_NOT_PLAYED INTEGER,
    GAMES_WON INTEGER,
    SCORE INTEGER,
    TOTAL_CARDS INTEGER,
    WARS_ELIGIBLE_FOR_PARTICIPATION INTEGER,
    WARS_PARTICIPATED INTEGER,
    primary key (date, league_span, player_tag)
);

ALTER TABLE PLAYER_AGGREGATION_WAR_STATS ADD CONSTRAINT PLAYER_AGGR_WAR_STAT_FK_PLAYER FOREIGN KEY(PLAYER_TAG) REFERENCES PLAYER(TAG);









