CREATE SEQUENCE PLAYER_IN_OUT_HIST_SEQUENCE start with 1 increment by 1;

CREATE TABLE PLAYER_IN_OUT_HISTORY (
    ID BIGINT NOT NULL,
    TAG VARCHAR(255) NOT NULL,
    CHECK_IN TIMESTAMP NOT NULL,
    CHECK_OUT TIMESTAMP,
    primary key (ID)
);

ALTER TABLE PLAYER_IN_OUT_HISTORY ADD CONSTRAINT PLAYER_IN_OUT_HISTORY_UNIQUE_1 UNIQUE (TAG, CHECK_IN);
ALTER TABLE PLAYER_IN_OUT_HISTORY ADD CONSTRAINT PLAYER_IN_OUT_HISTORY_PLAYER_FK FOREIGN KEY(TAG) REFERENCES PLAYER(TAG);
CREATE INDEX PLAYER_IN_OUT_HISTORY_INDEX ON PLAYER_IN_OUT_HISTORY (TAG, CHECK_IN);


CREATE SEQUENCE PLAYER_IN_OUT_SEQUENCE start with 1 increment by 1;

CREATE TABLE PLAYER_IN_OUT (
    ID BIGINT NOT NULL,
    TAG VARCHAR(255) NOT NULL,
    CHECK_IN TIMESTAMP NOT NULL,
    CHECK_OUT TIMESTAMP,
    primary key (ID)
);

ALTER TABLE PLAYER_IN_OUT ADD CONSTRAINT PLAYER_IN_OUT_UNIQUE_1 UNIQUE (TAG);
ALTER TABLE PLAYER_IN_OUT ADD CONSTRAINT PLAYER_IN_OUT_PLAYER_FK FOREIGN KEY(TAG) REFERENCES PLAYER(TAG);





