INSERT INTO player (tag,name,role) VALUES ('20RLV09G0','ERRIKOS ULTRAS','Member');
INSERT INTO player (tag,name,role) VALUES ('20VQP2Y0Y','panayiotis','Member');
INSERT INTO player (tag,name,role) VALUES ('222LLPCL9','thanosGr','Elder');
INSERT INTO player (tag,name,role) VALUES ('228RJJVQ0','panos_the_greek','Elder');
INSERT INTO player (tag,name,role) VALUES ('22ULY9LPL','KonVas DAB','Member');
INSERT INTO player (tag,name,role) VALUES ('29G99YYLY','aggelikikiller','Member');
INSERT INTO player (tag,name,role) VALUES ('29JYRL8LR','chris 13','Member');
INSERT INTO player (tag,name,role) VALUES ('29Q29RC2','stelios-v-01','Member');
INSERT INTO player (tag,name,role) VALUES ('2C0C9VUYL','XxEnderlordxX21','Member');
INSERT INTO player (tag,name,role) VALUES ('2CGR8JUP0','ΦονικόΡαπανάκι☺','Member');
INSERT INTO player (tag,name,role) VALUES ('2CPLV9JUG','George master 3','Member');
INSERT INTO player (tag,name,role) VALUES ('2GVCRLP9R','George master','Member');
INSERT INTO player (tag,name,role) VALUES ('2J29LCGVL','paris.z.2','Member');
INSERT INTO player (tag,name,role) VALUES ('2J9QPU0Y','jordan123','Member');
INSERT INTO player (tag,name,role) VALUES ('2JC22YCL2','panos','Member');
INSERT INTO player (tag,name,role) VALUES ('2JGGY989R','Hellspawn','Elder');
INSERT INTO player (tag,name,role) VALUES ('2L9QC022','Siou10','Member');
INSERT INTO player (tag,name,role) VALUES ('2LCL0LQC','Panos','Member');
INSERT INTO player (tag,name,role) VALUES ('2LPQ8VVGV','kostas9341','Member');
INSERT INTO player (tag,name,role) VALUES ('2P82UUYGG','Kiriakos Vins','Co-Leader');
INSERT INTO player (tag,name,role) VALUES ('2PC2PLCRG','paris z','Elder');
INSERT INTO player (tag,name,role) VALUES ('2Q8G80LLR','ΓΙΩΡΓΟΣ7','Member');
INSERT INTO player (tag,name,role) VALUES ('2QP09PJ','aggelos','Member');
INSERT INTO player (tag,name,role) VALUES ('2R2LUJG8L','aek','Member');
INSERT INTO player (tag,name,role) VALUES ('2RCL000UV','ronaldo','Member');
INSERT INTO player (tag,name,role) VALUES ('2VQJPJCLL','Mpak_Aliar','Member');
INSERT INTO player (tag,name,role) VALUES ('2Y2VCU82P','_t_a_s_o_s_','Member');
INSERT INTO player (tag,name,role) VALUES ('2Y8LYVLUQ','PANOS GREEK FTW','Elder');
INSERT INTO player (tag,name,role) VALUES ('2YQPVRUQ','Lord Con 2000','Member');
INSERT INTO player (tag,name,role) VALUES ('2YVLYLQ29','SUPERCELL','Member');
INSERT INTO player (tag,name,role) VALUES ('2YY0L99CL','The Boss 2','Member');
INSERT INTO player (tag,name,role) VALUES ('2YY8RGLC9','Vins','Member');
INSERT INTO player (tag,name,role) VALUES ('2YYR2R2Y8','Nasos.arv','Member');
INSERT INTO player (tag,name,role) VALUES ('80J2Q2UQC','#JIM#','Member');
INSERT INTO player (tag,name,role) VALUES ('80RJ8JG2','kostasbjj','Member');
INSERT INTO player (tag,name,role) VALUES ('82VLY2V9R','LastSaram','Elder');
INSERT INTO player (tag,name,role) VALUES ('8CG02J0J','PsHyCo G21','Member');
INSERT INTO player (tag,name,role) VALUES ('8JRC09JLC','aggelos3235','Member');
INSERT INTO player (tag,name,role) VALUES ('8LUCLJ298','yatagarasu','Elder');
INSERT INTO player (tag,name,role) VALUES ('8P0J88CQP','ntiana','Member');
INSERT INTO player (tag,name,role) VALUES ('8PY0RJR8G','dambo','Member');
INSERT INTO player (tag,name,role) VALUES ('8Q9PYCYYY','One-Eyed Jax','Member');
INSERT INTO player (tag,name,role) VALUES ('8QUYYPCJJ','lefsif77','Member');
INSERT INTO player (tag,name,role) VALUES ('8R8GG0RU8','Darnik','Member');
INSERT INTO player (tag,name,role) VALUES ('8U2RV0JRJ','vasiliki m','Member');
INSERT INTO player (tag,name,role) VALUES ('8U9UU99U2','games the games','Member');
INSERT INTO player (tag,name,role) VALUES ('8UVR0CV0','⚡️Panayiotis⚡️','Member');
INSERT INTO player (tag,name,role) VALUES ('8Y29YPPQC','_t_a_s_o_s_','Member');
INSERT INTO player (tag,name,role) VALUES ('8YGJU98QP','gkl','Member');
INSERT INTO player (tag,name,role) VALUES ('8YJUPQVYJ','konkon','Member');
INSERT INTO player (tag,name,role) VALUES ('8YP8CLY2C','Yannis','Member');
INSERT INTO player (tag,name,role) VALUES ('99G22RU20','padshadow','Member');
INSERT INTO player (tag,name,role) VALUES ('99URGR20G','yatagarasu2','Member');
INSERT INTO player (tag,name,role) VALUES ('9QRRUGJY','$tratos','Member');
INSERT INTO player (tag,name,role) VALUES ('9VU9V90L','Fighter','Member');
INSERT INTO player (tag,name,role) VALUES ('G99VPYPQ','IceWiZ TiTaN JR','Member');
INSERT INTO player (tag,name,role) VALUES ('GJ2GVLL9','lolman','Member');
INSERT INTO player (tag,name,role) VALUES ('GPCGPP0G','gtac.r.1','Member');
INSERT INTO player (tag,name,role) VALUES ('JPRJ92CJ','skeleton party','Member');
INSERT INTO player (tag,name,role) VALUES ('JU0GY2Y0','Skull Crasher','Member');
INSERT INTO player (tag,name,role) VALUES ('JVU90RPY','Lazaros','Member');
INSERT INTO player (tag,name,role) VALUES ('LUCQPYY','Mike Kampa 2','Elder');
INSERT INTO player (tag,name,role) VALUES ('P8J2Q9Q2','Pugly','Member');
INSERT INTO player (tag,name,role) VALUES ('PJ9VYC9G','manoskiller','Member');
INSERT INTO player (tag,name,role) VALUES ('PRVRLVCY','Βαγγελης Π.','Member');
INSERT INTO player (tag,name,role) VALUES ('PV0JGPYU','CraZyRapTor','Member');
INSERT INTO player (tag,name,role) VALUES ('Q9PL9L8G','Lukas Mafiozos','Member');
INSERT INTO player (tag,name,role) VALUES ('QQV9L00Y','kots13','Leader');
INSERT INTO player (tag,name,role) VALUES ('QULVR02C','theodore','Member');
INSERT INTO player (tag,name,role) VALUES ('R9RYUQJG','kyrmamous2016','Member');
INSERT INTO player (tag,name,role) VALUES ('RG99QUCV','TheGreek','Member');
INSERT INTO player (tag,name,role) VALUES ('RGQUR2JU','Chris Master','Member');
INSERT INTO player (tag,name,role) VALUES ('U8Y0GPGY','apo#14','Member');
INSERT INTO player (tag,name,role) VALUES ('ULUYPJY0','aggeliki kiler','Member');
INSERT INTO player (tag,name,role) VALUES ('UY9UR2Y2','barbarian king','Member');
INSERT INTO player (tag,name,role) VALUES ('V2R8U89U','Dark Skeleton','Member');
INSERT INTO player (tag,name,role) VALUES ('VVQLYP2C','Omega','Member');
INSERT INTO player (tag,name,role) VALUES ('Y089RV8R','AggelosZ','Member');
INSERT INTO player (tag,name,role) VALUES ('Y2VYVRR0','Siou_10','Member');
INSERT INTO player (tag,name,role) VALUES ('YCRPPCRQ','Chris Master','Member');
INSERT INTO player (tag,name,role) VALUES ('YLCL0V8G','thanos','Member');
INSERT INTO player (tag,name,role) VALUES ('YP0VPJP8','tasos21','Elder');
INSERT INTO player (tag,name,role) VALUES ('YYJGL22Q','Supercell','Member');


INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (1,636,45,35,'222LLPCL9',636.0,45.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (2,34,7,35,'LUCQPYY',34.0,7.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (3,394,54,35,'QQV9L00Y',394.0,54.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (4,138,65,35,'2PC2PLCRG',138.0,65.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (5,833,78,35,'2P82UUYGG',833.0,78.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (6,0,0,35,'2L9QC022',0.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (7,22,0,35,'YLCL0V8G',22.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (8,116,24,35,'UY9UR2Y2',116.0,24.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (9,197,5,35,'Y2VYVRR0',197.0,5.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (10,312,16,35,'8LUCLJ298',312.0,16.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (11,0,0,35,'8CG02J0J',0.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (12,607,56,35,'QULVR02C',607.0,56.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (13,302,2,35,'VVQLYP2C',302.0,2.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (14,0,0,35,'8UVR0CV0',0.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (15,539,33,35,'YCRPPCRQ',539.0,33.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (16,334,45,35,'JPRJ92CJ',334.0,45.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (17,226,26,35,'2YY8RGLC9',226.0,26.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (18,150,12,35,'20VQP2Y0Y',150.0,12.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (19,476,13,35,'JU0GY2Y0',476.0,13.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (20,249,31,35,'2GVCRLP9R',249.0,31.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (21,100,5,35,'GPCGPP0G',100.0,5.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (22,633,110,35,'V2R8U89U',633.0,110.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (23,1138,88,35,'YP0VPJP8',1138.0,88.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (24,42,0,35,'G99VPYPQ',42.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (25,105,6,35,'JVU90RPY',105.0,6.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (26,72,0,35,'2LCL0LQC',72.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (27,6,0,35,'9QRRUGJY',6.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (28,24,0,35,'Y089RV8R',24.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (29,307,45,35,'RG99QUCV',307.0,45.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (30,946,33,35,'PJ9VYC9G',946.0,33.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (31,187,15,35,'80J2Q2UQC',187.0,15.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (32,321,23,35,'228RJJVQ0',321.0,23.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (33,340,18,35,'2QP09PJ',340.0,18.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (34,690,330,35,'82VLY2V9R',690.0,330.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (35,480,183,35,'2JGGY989R',480.0,183.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (36,0,0,35,'2J29LCGVL',0.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (37,6,8,35,'PRVRLVCY',6.0,8.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (38,0,0,35,'2CGR8JUP0',0.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (39,0,0,35,'2CPLV9JUG',0.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (40,0,0,35,'8YGJU98QP',0.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (41,146,0,35,'U8Y0GPGY',146.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (42,119,11,35,'29JYRL8LR',119.0,11.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (43,247,95,35,'2VQJPJCLL',247.0,95.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (44,56,8,35,'RGQUR2JU',56.0,8.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (45,4,16,35,'2Y8LYVLUQ',4.0,16.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (46,16,0,35,'2RCL000UV',16.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (47,60,0,35,'8Y29YPPQC',60.0,0.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (48,12,16,35,'8P0J88CQP',12.0,16.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (49,48,39,35,'8PY0RJR8G',48.0,39.0);
INSERT INTO player_weekly_stats (id,card_donation,chest_contribution,week,playerfk,avg_card_donation,avg_chest_contribution) VALUES (50,80,40,35,'8YP8CLY2C',80.0,40.0);